name: "CI: pliron-llvm (no-default-features)"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Test pliron-llvm (no-default-features)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable

    - uses: Swatinem/rust-cache@v2

    - name: Clippy pliron-llvm - no default features
      run: cargo clippy -p pliron-llvm --all-targets --no-default-features -- -D warnings

    # `std` without `llvm-sys`: Make sure that pliron is built with `std` on.
    - name: Clippy pliron-llvm - std, no llvm-sys
      run: cargo clippy -p pliron-llvm --no-default-features --features std -- -D warnings

    # Same as the previous one
    - name: Build pliron-llvm - std, no llvm-sys
      run: RUSTFLAGS="-D warnings" cargo build -p pliron-llvm --no-default-features --features std --verbose

    - name: Test debug pliron-llvm - no default features
      run: RUSTFLAGS="-D warnings" cargo test -p pliron-llvm --no-default-features --verbose

    - name: Test release pliron-llvm - no default features
      run: RUSTFLAGS="-D warnings" cargo test -p pliron-llvm --no-default-features --release --verbose

    - name: Documentation pliron-llvm - no default features
      run: RUSTDOCFLAGS="-D warnings" cargo doc -p pliron-llvm --no-default-features --verbose
